accepted = [
    "MIT",
    "ISC",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "Apache-2.0",
    "MPL-2.0",
    "LGPL-3.0",
    "Unicode-DFS-2016",
    "OpenSSL",
]

# Ring has all the licenses combined into a single file, which causes cargo about to 
# be confused about it. Thankfully it includes a workaround for this that we can enable.
workarounds = ["ring"]
