[package]
name = "sdk-schemas"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
internal = ["bitwarden-json/internal"] # Internal testing methods
performance-testing = ["bitwarden-json/performance-testing"] # Performance testing methods

[dependencies]
schemars = { version = "0.8.12",  features = ["preserve_order"] }
serde_json = "1.0.96"
anyhow = "1.0.71"
itertools = "0.11.0"

bitwarden = { path = "../bitwarden" }
bitwarden-json = { path = "../bitwarden-json" }
