[package]
name = "sdk-schemas"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemars = "0.8.12"
serde_json = "1.0.96"
anyhow = "1.0.71"
itertools = "0.10.5"

bitwarden = { path = "../bitwarden" }
bitwarden-json = { path = "../bitwarden-json" }
