[package]
name = "sdk-schemas"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

[features]
internal = ["bitwarden/internal", "bitwarden-json/internal"]

[dependencies]
schemars = { version = "0.8.12",  features = ["preserve_order"] }
serde_json = "1.0.96"
anyhow = "1.0.71"
itertools = "0.11.0"

bitwarden = { path = "../bitwarden" }
bitwarden-json = { path = "../bitwarden-json" }
