[build-system]
build-backend = "maturin"
requires = ["maturin>=1.0,<2.0", "setuptools_rust>=1.8.1"]

[project]
authors = [{ name = "Bitwarden", email = "support@bitwarden.com" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: Other/Proprietary License",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Rust",
  "Topic :: Security",
]
dependencies = ["dateutils >= 0.6.6"]
description = "A Bitwarden Client for python"
name = "bitwarden_sdk"
readme = "README.md"
requires-python = ">=3.0"
version = "0.1.0"

[tool.maturin]
bindings = "pyo3"
compatibility = "manylinux2014"
include = [
  { path = "bitwarden_sdk/*.py", format = ["sdist", "wheel"] }
]
manifest-path = "../../crates/bitwarden-py/Cargo.toml"
python-packages = ["bitwarden_sdk"]
