[package]
name = "bitwarden-cli"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
color-eyre = "0.6"
supports-color = "2.0.0"
