[package]
name = "uniffi-bindgen"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

[[bin]]
# This can be whatever name makes sense for your project, but the rest of this tutorial assumes uniffi-bindgen.
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
uniffi = { version = "=0.26.1", features = ["cli"] }
