---
name: Delete old packages

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  delete:
    name: Cleanup Android SDK
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with:
          package-name: com.bitwarden.sdk-android
          package-type: maven
          min-versions-to-keep: 25

          # Ignore versions only containing version numbers
          ignore-versions: '^\d*\.\d*\.\d*(-SNAPSHOT)?$'
